"""
    PasteUrl CRUD urils for the database.
    Copyright (C) 2022-2023 Stepan Zubkov <stepanzubkov@florgon.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from hashids import Hashids
from flask_sqlalchemy import SQLAlchemy
from flask import current_app

from app.database.models.url import PasteUrl


def create_url(
    db: SQLAlchemy,
    content: str,
    stats_is_public: bool = False,
    burn_after_read: bool = False,
    language: str | None = "plain",
    owner_id: int | None = None,
) -> PasteUrl:
    """
    Creates new shortened paste url in database.
    :param SQLAlchemy db: database object
    :param str content: paste text content
    :param bool stats_is_public: makes url stats public to all users
    :param bool burn_after_read: deletes url after first reading
    :param int | None owner_id: id of local user
    :return: created url object
    :rtype: RedirectUrl
    """
    url = PasteUrl(
        content=content,
        stats_is_public=stats_is_public,
        burn_after_read=burn_after_read,
        owner_id=owner_id,
        language=language,
    )

    db.session.add(url)
    db.session.commit()
    db.session.refresh(url)

    return url


def get_by_owner_id(owner_id: int) -> list[PasteUrl]:
    """
    Returns PasteUrls with specified owner_id.
    :param int owner_id: id of owner
    :return: List with URLs.
    :rtype: list[PasteUrl]
    """
    return PasteUrl.query.filter_by(owner_id=owner_id)


def get_by_hash(url_hash: str, only_active: bool = True) -> PasteUrl | None:
    """
    Get paste url from database by hash generated by hashids.
    Decodes hash and get url from database by decoded id.
    :param SQLAlchemy db: database object
    :param str url_hash: hashids hash
    :param bool only_active: search url from active (with is_deleted = False) urls
    :return: url object
    :rtype: PasteUrl or None if hash is invalid
    """
    hashids = Hashids(salt=current_app.config["HASHIDS_SALT"], min_length=6)
    url_ids: tuple[int] = hashids.decode(url_hash)
    if len(url_ids) != 1:
        return None
    url_id = url_ids[0]
    url = PasteUrl.query.filter_by(id=url_id)
    if only_active:
        url = url.filter_by(is_deleted=False)
    return url.first()


def delete(db: SQLAlchemy, url: PasteUrl) -> None:
    """
    Deletes paste url and views.
    :param SQLAlchemy db: database object
    :param PasteUrl url: url object
    """
    url.is_deleted = True
    db.session.commit()


def update(db: SQLAlchemy, url: PasteUrl, text: str | None = None, language: str | None = None) -> PasteUrl:
    """
    Updates paste url (text).
    :param SQLAlchemy db: database object
    :param PasteUrl url: paste object
    :param str text: new paste text
    """
    if text:
        url.content = text
    if language:
        url.language = language
    db.session.commit()
    db.session.refresh(url)
    return url
