"""
    Url CRUD utils for the database.
"""
from flask import current_app
from flask_sqlalchemy import SQLAlchemy
from hashids import Hashids

from app.database.models.url import Url


def create_url(db: SQLAlchemy, redirect_url: str, stats_is_public: bool = False) -> Url:
    """
    Creates new shortened url in database.
    :param SQLAlchemy db: database object
    :param str redirect_url: long url for redirecting
    :return: created url object
    :rtype: Url
    """
    if not redirect_url.startswith("http://") and not redirect_url.startswith(
        "https://"
    ):
        # Add protocol for valid redirecting to an external domain
        redirect_url = "https://" + redirect_url

    url = Url(
        redirect=redirect_url,
        stats_is_public=stats_is_public,
    )

    db.session.add(url)
    db.session.commit()
    db.session.refresh(url)

    return url


def get_by_hash(hash: str) -> Url | None:
    """
    Get shortened url from database by hash generated by hashids.
    Decodes hash and get url from database by decoded id.
    :param SQLAlchemy db: database object
    :param str hash: hashids hash
    :return: url object
    :rtype: Url or None if hash is invalid
    """
    hashids = Hashids(salt=current_app.config["HASHIDS_SALT"])
    url_ids: tuple[int] = hashids.decode(hash)
    if len(url_ids) != 1:
        return None
    url_id = url_ids[0]
    url = Url.query.filter_by(id=url_id).first()
    return url


def add_view(db: SQLAlchemy, url: Url) -> Url:
    """
    Adds view to url stats before redirecting.
    :param SQLAlchemy db: database object
    :param Url url: url object
    :return: updated url object
    :rtype: Url
    """
    url.views += 1
    db.session.commit()
    db.session.refresh(url)

    return url


def delete(db: SQLAlchemy, url: Url) -> None:
    """
    Deletes url and views.
    :param SQLAlchemy db: database object
    :param Url url: url object
    """
    db.session.delete(url)
    db.session.commit()
