"""Add stats_is_public flag to url

Revision ID: 06e067e43a7f
Revises: afbed5eafaf9
Create Date: 2022-12-22 09:10:16.662748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "06e067e43a7f"
down_revision = "afbed5eafaf9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.add_column(sa.Column("stats_is_public", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.drop_column("stats_is_public")

    # ### end Alembic commands ###
