"""Add is_deleted field for url

Revision ID: 1425860a09ef
Revises: 06e067e43a7f
Create Date: 2022-12-24 16:30:45.752348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1425860a09ef"
down_revision = "06e067e43a7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_deleted", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.drop_column("is_deleted")

    # ### end Alembic commands ###
