"""Remove statistics from paste_url

Revision ID: 23b440a368ef
Revises: 61d843cf9779
Create Date: 2023-02-18 16:05:32.932481

Copyright (C) 2022-2023 Stepan Zubkov <stepanzubkov@florgon.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b440a368ef'
down_revision = '61d843cf9779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paste_urls', schema=None) as batch_op:
        batch_op.drop_column('stats_is_public')

    with op.batch_alter_table('url_views', schema=None) as batch_op:
        batch_op.drop_constraint('url_views_paste_id_fkey', type_='foreignkey')
        batch_op.drop_column('paste_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paste_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('url_views_paste_id_fkey', 'paste_urls', ['paste_id'], ['id'])

    with op.batch_alter_table('paste_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stats_is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
