"""Remove statistics from paste_url

Revision ID: 23b440a368ef
Revises: 61d843cf9779
Create Date: 2023-02-18 16:05:32.932481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b440a368ef'
down_revision = '61d843cf9779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paste_urls', schema=None) as batch_op:
        batch_op.drop_column('stats_is_public')

    with op.batch_alter_table('url_views', schema=None) as batch_op:
        batch_op.drop_constraint('url_views_paste_id_fkey', type_='foreignkey')
        batch_op.drop_column('paste_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paste_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('url_views_paste_id_fkey', 'paste_urls', ['paste_id'], ['id'])

    with op.batch_alter_table('paste_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stats_is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
