"""Add stats_is_public to urls

Revision ID: 30042365eea2
Revises: 23b440a368ef
Create Date: 2023-02-25 08:53:16.291279

Copyright (C) 2022-2023 Stepan Zubkov <stepanzubkov@florgon.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30042365eea2'
down_revision = '23b440a368ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paste_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stats_is_public', sa.Boolean(), nullable=True))

    with op.batch_alter_table('url_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paste_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'paste_urls', ['paste_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_views', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('paste_id')

    with op.batch_alter_table('paste_urls', schema=None) as batch_op:
        batch_op.drop_column('stats_is_public')

    # ### end Alembic commands ###
