"""Add stats_is_public to urls

Revision ID: 30042365eea2
Revises: 23b440a368ef
Create Date: 2023-02-25 08:53:16.291279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30042365eea2'
down_revision = '23b440a368ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paste_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stats_is_public', sa.Boolean(), nullable=True))

    with op.batch_alter_table('url_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paste_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'paste_urls', ['paste_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_views', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('paste_id')

    with op.batch_alter_table('paste_urls', schema=None) as batch_op:
        batch_op.drop_column('stats_is_public')

    # ### end Alembic commands ###
