"""Add new user model

Revision ID: 37da9760b337
Revises: e3facbdd6e2d
Create Date: 2024-02-17 17:07:42.726207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37da9760b337'
down_revision = 'e3facbdd6e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paste_urls', schema=None) as batch_op:
        batch_op.drop_constraint('paste_urls_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('redirect_urls', schema=None) as batch_op:
        batch_op.drop_constraint('redirect_urls_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=1000), nullable=False))
        batch_op.drop_constraint('users_user_id_key', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_user_id_key', ['user_id'])
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    with op.batch_alter_table('redirect_urls', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('redirect_urls_owner_id_fkey', 'users', ['owner_id'], ['user_id'])

    with op.batch_alter_table('paste_urls', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('paste_urls_owner_id_fkey', 'users', ['owner_id'], ['user_id'])

    # ### end Alembic commands ###
