"""empty message

Revision ID: 480b4604ec7a
Revises: d3efc51eb2c2
Create Date: 2022-12-25 17:55:13.532918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "480b4604ec7a"
down_revision = "d3efc51eb2c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_agent", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_agent_value", sa.String(length=250), nullable=False)
        )
        batch_op.drop_column("value")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_agent", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "value", sa.VARCHAR(length=250), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column("user_agent_value")

    # ### end Alembic commands ###
