"""Change PasteUrl.content type to sqlalchemy String

Revision ID: 61d843cf9779
Revises: c8bf423b6a5f
Create Date: 2023-02-12 08:41:33.500081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d843cf9779'
down_revision = 'c8bf423b6a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paste_urls', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=4096),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paste_urls', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=4096),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
