"""Add boolean flag burn_after_read to paste url

Revision ID: 7b046c164e41
Revises: 30042365eea2
Create Date: 2023-05-13 12:16:19.034809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b046c164e41'
down_revision = '30042365eea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paste_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('burn_after_read', sa.Boolean(), nullable=False, server_default="false"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paste_urls', schema=None) as batch_op:
        batch_op.drop_column('burn_after_read')

    # ### end Alembic commands ###
