"""empty message

Revision ID: 825a265cf834
Revises: 1425860a09ef
Create Date: 2022-12-25 14:03:30.631653

Copyright (C) 2022-2023 Stepan Zubkov <stepanzubkov@florgon.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "825a265cf834"
down_revision = "1425860a09ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_agent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "url_view",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip", sa.String(length=15), nullable=False),
        sa.Column("user_agent_id", sa.Integer(), nullable=False),
        sa.Column("view_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_agent_id"],
            ["user_agent.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("url_view")
    op.drop_table("user_agent")
    # ### end Alembic commands ###
