"""empty message

Revision ID: 825a265cf834
Revises: 1425860a09ef
Create Date: 2022-12-25 14:03:30.631653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825a265cf834'
down_revision = '1425860a09ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('view_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_agent_id'], ['user_agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_view')
    op.drop_table('user_agent')
    # ### end Alembic commands ###
