"""empty message

Revision ID: d3efc51eb2c2
Revises: 825a265cf834
Create Date: 2022-12-25 17:28:05.383487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3efc51eb2c2"
down_revision = "825a265cf834"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.drop_column("views")

    with op.batch_alter_table("url_view", schema=None) as batch_op:
        batch_op.add_column(sa.Column("url_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "url", ["url_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url_view", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("url_id")

    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("views", sa.INTEGER(), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
