"""empty message

Revision ID: d3efc51eb2c2
Revises: 825a265cf834
Create Date: 2022-12-25 17:28:05.383487

Copyright (C) 2022-2023 Stepan Zubkov <stepanzubkov@florgon.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3efc51eb2c2"
down_revision = "825a265cf834"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.drop_column("views")

    with op.batch_alter_table("url_view", schema=None) as batch_op:
        batch_op.add_column(sa.Column("url_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "url", ["url_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url_view", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("url_id")

    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("views", sa.INTEGER(), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
