"""Add language field

Revision ID: e3facbdd6e2d
Revises: 7b046c164e41
Create Date: 2023-07-08 18:47:52.104463

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e3facbdd6e2d"
down_revision = "7b046c164e41"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("paste_urls", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("language", sa.String(), server_default="plain", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("paste_urls", schema=None) as batch_op:
        batch_op.drop_column("language")

    # ### end Alembic commands ###
