"""refactor url models, remove url_views model

Revision ID: f4b5db915adb
Revises: 5f9cee34c025
Create Date: 2023-02-07 19:39:44.623280

Copyright (C) 2022-2023 Stepan Zubkov <stepanzubkov@florgon.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4b5db915adb'
down_revision = '5f9cee34c025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paste_urls',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('stats_is_public', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redirect_urls',
    sa.Column('redirect', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('stats_is_public', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('url_views')
    op.drop_table('urls')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_views',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ip', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('user_agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('referer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['referer_id'], ['referers.id'], name='url_views_referer_id_fkey'),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], name='url_views_url_id_fkey'),
    sa.ForeignKeyConstraint(['user_agent_id'], ['user_agents.id'], name='url_views_user_agent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='url_views_pkey')
    )
    op.create_table('urls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('redirect', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stats_is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], name='urls_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='urls_pkey')
    )
    op.create_table('referers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referer_value', sa.VARCHAR(length=4096), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='referers_pkey')
    )
    op.drop_table('redirect_urls')
    op.drop_table('paste_urls')
    # ### end Alembic commands ###
