name: Linters (Pylint, MyPy)

on:
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linters
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install --upgrade pip
        working-directory: "src/"
      - name: Install linters
        run: pip install pylint==v3.0.0a3 mypy==v0.902
        working-directory: "src/app/"
      - name: PyLint lint.
        run: pylint $(git ls-files '*.py')
        working-directory: "src/app/"
      - name: All PyLint warning.
        run: pylint $(git ls-files '*.py') || true
        working-directory: "src/app/"
      - name: MyPy type check.
        working-directory: "src/app/"
        run: mypy $(git ls-files '*.py') || true
